# Generated by Django 4.0 on 2021-12-31 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api', '0002_alter_rating_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'meal')},
        ),
        migrations.AlterIndexTogether(
            name='rating',
            index_together={('user', 'meal')},
        ),
    ]
